import React, { createContext, useState, useContext, ReactNode } from 'react';

export type Language = 'en' | 'zh';

export const translations = {
  en: {
    appTitle: "Eat & Care",
    navKitchen: "Smart Kitchen",
    navCookbook: "My Cookbook",
    navSafety: "Food Safety",
    navRecovery: "Sick & Recovery",
    store: "Store",
    aiRecipes: "AI Recipes",
    myBook: "My Book",
    safety: "Safety",
    recovery: "Recovery",
    clinicalMode: "Clinical Mode: Active",
    foodCompatibility: "Food Compatibility",
    didYouKnow: "Did you know combining calcium-rich foods with iron sources can reduce iron absorption by up to 60%? Check the Food Safety tab for details.",
    checkSafety: "Check Food Safety",
    recommendedRecipes: "Recommended Recipes",
    awaitingAnalysis: "Awaiting Analysis",
    resultsFound: "results found",
    startJourney: "Start your journey",
    startJourneyDesc: "Add ingredients to your Store tab and define your health constraints to generate clinical-grade recipes.",
    goToStore: "Go to Store",
    viewAnalysis: "View Analysis & Recipe",
    loadMore: "Load More Recipes",
    ingredientStore: "Ingredient Store",
    autoSaved: "Auto-saved",
    items: "Items",
    addItemPlaceholder: "Add item...",
    scanCamera: "Scan ingredients with camera",
    analyzingImage: "Analyzing image...",
    emptyStore: "Your store is empty. Key in ingredients or scan a photo to save them for later.",
    analyzeGenerate: "Analyze & Generate Recipes",
    clinicalProfile: "Clinical Profile",
    exclusionsPreferences: "Exclusions & Preferences",
    contraindications: "Contraindications",
    dislikes: "Dislikes",
    addAllergyPlaceholder: "Add allergy...",
    addDislikePlaceholder: "Add dislike...",
    noAllergies: "No known allergies logged.",
    noDislikes: "No dislikes logged.",
    safetyTitle: "Food Safety",
    safetySubtitle: "Search for any ingredient to discover its biochemical synergies and clinical contraindications.",
    enterFoodPlaceholder: "Enter food name (e.g. Tofu, Spinach, Antibiotics...)",
    analyze: "Analyze",
    analysisReport: "Clinical Report",
    synergisticPairings: "Synergistic Pairings",
    contraindicationsRisk: "Contraindications (Risk Order)",
    noSynergies: "No strong synergies found.",
    noConflicts: "No significant conflicts found.",
    recoveryTitle: "Sick & Recovery",
    recoverySubtitle: "Get clinical dietary protocols tailored to your current health condition or symptoms.",
    enterConditionPlaceholder: "Enter conditions (e.g. Flu and Cough, Migraine...)",
    getProtocol: "Get Protocol",
    quickAccess: "Quick Access:",
    protocol: "Protocol",
    clinicalAdvice: "Clinical Advice",
    canIEatThis: "Can I eat this?",
    checkFoodPlaceholder: "e.g. Ice Cream, Toast, Orange Juice...",
    check: "Check",
    beneficialEat: "Beneficial (Eat)",
    contraindicatedAvoid: "Contraindicated (Avoid)",
    lifestyleTips: "Clinical Lifestyle Tips",
    checkIfSafe: "Check if a specific food is safe for",
    createRecipe: "Create Recipe",
    noRecipesYet: "No recipes yet",
    startBuilding: "Start building your personal cookbook by adding your favorite dishes.",
    createFirst: "Create First Recipe",
    saveRecipe: "Save Recipe",
    recipeName: "Recipe Name *",
    description: "Description",
    servings: "Servings / Portion",
    ingredients: "Ingredients",
    instructions: "Instructions / Steps",
    addItem: "Add Item",
    addStep: "Add Step",
    cancel: "Cancel",
    recipeImage: "Recipe Image",
    clickToUpload: "Click to upload",
    changeImage: "Change Image",
    processing: "Processing...",
    errorImageTooLarge: "Image is too large. Please select an image under 5MB.",
    bioCompatible: "Bio-Compatible",
    noKnownConflicts: "No known nutrient inhibition or conflicts detected.",
    clinicalInteraction: "Clinical Interaction Detected",
    nutritionProfile: "Nutrition Profile",
    calories: "Calories",
    micronutrients: "Micronutrients",
    nutritionalValuesEstimate: "Nutritional values are estimates based on standard ingredient data.",
    noAnalysisData: "No Analysis Data",
    noAnalysisDataDesc: "Nutritional data is not available for manually created recipes yet.",
    missing: "Missing",
    match: "Match",
    caution: "Caution",
    myRecipe: "My Recipe",
    flu: "Flu",
    soreThroat: "Sore Throat",
    fever: "Fever",
    menstruation: "Menstruation",
    cough: "Cough"
  },
  zh: {
    appTitle: "Eat & Care",
    navKitchen: "智能厨房",
    navCookbook: "我的食谱",
    navSafety: "食品安全",
    navRecovery: "生病与康复",
    store: "储藏室",
    aiRecipes: "AI食谱",
    myBook: "食谱书",
    safety: "安全检查",
    recovery: "康复指南",
    clinicalMode: "临床模式：已激活",
    foodCompatibility: "食物相克与协同",
    didYouKnow: "您知道吗？高钙食物与含铁食物同食会降低高达60%的铁吸收率。详情请查看食品安全标签。",
    checkSafety: "检查食品安全",
    recommendedRecipes: "推荐食谱",
    awaitingAnalysis: "等待分析",
    resultsFound: "个结果",
    startJourney: "开始您的健康之旅",
    startJourneyDesc: "在储藏室添加食材并定义您的健康限制，生成临床级食谱。",
    goToStore: "前往储藏室",
    viewAnalysis: "查看分析与食谱",
    loadMore: "加载更多食谱",
    ingredientStore: "食材储藏室",
    autoSaved: "自动保存",
    items: "项",
    addItemPlaceholder: "添加食材...",
    scanCamera: "拍照扫描食材",
    analyzingImage: "正在分析图片...",
    emptyStore: "您的储藏室是空的。请输入食材或拍照保存。",
    analyzeGenerate: "分析并生成食谱",
    clinicalProfile: "临床档案",
    exclusionsPreferences: "禁忌与偏好",
    contraindications: "禁忌/过敏",
    dislikes: "不喜欢的食物",
    addAllergyPlaceholder: "添加过敏原...",
    addDislikePlaceholder: "添加不喜欢的食物...",
    noAllergies: "暂无过敏记录。",
    noDislikes: "暂无记录。",
    safetyTitle: "食品安全检查",
    safetySubtitle: "搜索任何食材以发现其生化协同作用和临床禁忌。",
    enterFoodPlaceholder: "输入食物名称 (如：豆腐, 菠菜, 抗生素...)",
    analyze: "分析",
    analysisReport: "临床报告",
    synergisticPairings: "协同搭配 (有益)",
    contraindicationsRisk: "禁忌搭配 (风险排序)",
    noSynergies: "未发现显著的协同作用。",
    noConflicts: "未发现显著的冲突。",
    recoveryTitle: "生病与康复",
    recoverySubtitle: "根据您当前的健康状况或症状获取临床饮食方案。",
    enterConditionPlaceholder: "输入症状 (如：流感, 咳嗽, 偏头痛...)",
    getProtocol: "获取方案",
    quickAccess: "快速访问:",
    protocol: "方案",
    clinicalAdvice: "临床建议",
    canIEatThis: "我能吃这个吗？",
    checkFoodPlaceholder: "如：冰淇淋, 土司, 橙汁...",
    check: "检查",
    beneficialEat: "有益 (宜食)",
    contraindicatedAvoid: "禁忌 (忌食)",
    lifestyleTips: "临床生活建议",
    checkIfSafe: "检查特定食物是否适合",
    createRecipe: "创建食谱",
    noRecipesYet: "暂无食谱",
    startBuilding: "通过添加您喜欢的菜肴来建立您的个人食谱。",
    createFirst: "创建第一个食谱",
    saveRecipe: "保存食谱",
    recipeName: "食谱名称 *",
    description: "描述",
    servings: "份量",
    ingredients: "食材",
    instructions: "步骤 / 说明",
    addItem: "添加项目",
    addStep: "添加步骤",
    cancel: "取消",
    recipeImage: "食谱图片",
    clickToUpload: "点击上传",
    changeImage: "更改图片",
    processing: "处理中...",
    errorImageTooLarge: "图片太大。请选择小于 5MB 的图片。",
    bioCompatible: "生物相容",
    noKnownConflicts: "未检测到已知的营养抑制或冲突。",
    clinicalInteraction: "检测到临床相互作用",
    nutritionProfile: "营养概况",
    calories: "卡路里",
    micronutrients: "微量营养素",
    nutritionalValuesEstimate: "营养价值是基于标准成分数据的估算值。",
    noAnalysisData: "无分析数据",
    noAnalysisDataDesc: "手动创建的食谱暂无营养数据。",
    missing: "缺失",
    match: "匹配",
    caution: "注意",
    myRecipe: "我的食谱",
    flu: "流感",
    soreThroat: "咽喉痛",
    fever: "发烧",
    menstruation: "月经",
    cough: "咳嗽"
  }
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: typeof translations.en;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');
  
  const value = {
    language,
    setLanguage,
    t: translations[language]
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
